name: Publish to Maven Central

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish to Maven Central
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # sbt-dynver needs full git history

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up sbt
        uses: sbt/setup-sbt@v1

      - name: Publish Scala 2.13
        run: sbt ++2.13.14 ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.GPG_PRIVATE_KEY }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}

      - name: Publish Scala 2.12
        run: sbt ++2.12.18 ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.GPG_PRIVATE_KEY }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
